from sqlalchemy.orm import Session

from app.db.base import Base
from app.db.session import engine
from app.models import country, image, place, user  # noqa: F401 – register models


SEED_COUNTRIES = [
    {"name": "Afghanistan", "iso_code": "AF", "latitude": 33.93, "longitude": 67.71},
    {"name": "Albania", "iso_code": "AL", "latitude": 41.15, "longitude": 20.17},
    {"name": "Algeria", "iso_code": "DZ", "latitude": 28.03, "longitude": 1.66},
    {"name": "Andorra", "iso_code": "AD", "latitude": 42.55, "longitude": 1.60},
    {"name": "Angola", "iso_code": "AO", "latitude": -11.20, "longitude": 17.87},
    {"name": "Antigua and Barbuda", "iso_code": "AG", "latitude": 17.06, "longitude": -61.80},
    {"name": "Argentina", "iso_code": "AR", "latitude": -38.42, "longitude": -63.62},
    {"name": "Armenia", "iso_code": "AM", "latitude": 40.07, "longitude": 45.04},
    {"name": "Australia", "iso_code": "AU", "latitude": -25.27, "longitude": 133.78},
    {"name": "Austria", "iso_code": "AT", "latitude": 47.52, "longitude": 14.55},
    {"name": "Azerbaijan", "iso_code": "AZ", "latitude": 40.14, "longitude": 47.58},
    {"name": "Bahamas", "iso_code": "BS", "latitude": 25.03, "longitude": -77.40},
    {"name": "Bahrain", "iso_code": "BH", "latitude": 26.00, "longitude": 50.55},
    {"name": "Bangladesh", "iso_code": "BD", "latitude": 23.68, "longitude": 90.36},
    {"name": "Barbados", "iso_code": "BB", "latitude": 13.19, "longitude": -59.54},
    {"name": "Belarus", "iso_code": "BY", "latitude": 53.71, "longitude": 27.95},
    {"name": "Belgium", "iso_code": "BE", "latitude": 50.50, "longitude": 4.47},
    {"name": "Belize", "iso_code": "BZ", "latitude": 17.19, "longitude": -88.50},
    {"name": "Benin", "iso_code": "BJ", "latitude": 9.31, "longitude": 2.32},
    {"name": "Bhutan", "iso_code": "BT", "latitude": 27.51, "longitude": 90.43},
    {"name": "Bolivia", "iso_code": "BO", "latitude": -16.29, "longitude": -63.59},
    {"name": "Bosnia and Herzegovina", "iso_code": "BA", "latitude": 43.92, "longitude": 17.68},
    {"name": "Botswana", "iso_code": "BW", "latitude": -22.33, "longitude": 24.68},
    {"name": "Brazil", "iso_code": "BR", "latitude": -14.24, "longitude": -51.93},
    {"name": "Brunei", "iso_code": "BN", "latitude": 4.54, "longitude": 114.73},
    {"name": "Bulgaria", "iso_code": "BG", "latitude": 42.73, "longitude": 25.49},
    {"name": "Burkina Faso", "iso_code": "BF", "latitude": 12.36, "longitude": -1.56},
    {"name": "Burundi", "iso_code": "BI", "latitude": -3.37, "longitude": 29.92},
    {"name": "Cabo Verde", "iso_code": "CV", "latitude": 16.54, "longitude": -23.04},
    {"name": "Cambodia", "iso_code": "KH", "latitude": 12.57, "longitude": 104.99},
    {"name": "Cameroon", "iso_code": "CM", "latitude": 3.85, "longitude": 11.50},
    {"name": "Canada", "iso_code": "CA", "latitude": 56.13, "longitude": -106.35},
    {"name": "Central African Republic", "iso_code": "CF", "latitude": 6.61, "longitude": 20.94},
    {"name": "Chad", "iso_code": "TD", "latitude": 15.45, "longitude": 18.73},
    {"name": "Chile", "iso_code": "CL", "latitude": -35.68, "longitude": -71.54},
    {"name": "China", "iso_code": "CN", "latitude": 35.86, "longitude": 104.20},
    {"name": "Colombia", "iso_code": "CO", "latitude": 4.57, "longitude": -74.30},
    {"name": "Comoros", "iso_code": "KM", "latitude": -11.64, "longitude": 43.33},
    {"name": "Congo", "iso_code": "CG", "latitude": -0.23, "longitude": 15.83},
    {"name": "Congo, Democratic Republic of", "iso_code": "CD", "latitude": -4.04, "longitude": 21.76},
    {"name": "Costa Rica", "iso_code": "CR", "latitude": 9.75, "longitude": -83.75},
    {"name": "Croatia", "iso_code": "HR", "latitude": 45.10, "longitude": 15.20},
    {"name": "Cuba", "iso_code": "CU", "latitude": 21.52, "longitude": -77.78},
    {"name": "Cyprus", "iso_code": "CY", "latitude": 35.13, "longitude": 33.43},
    {"name": "Czechia", "iso_code": "CZ", "latitude": 49.82, "longitude": 15.47},
    {"name": "Denmark", "iso_code": "DK", "latitude": 56.26, "longitude": 9.50},
    {"name": "Djibouti", "iso_code": "DJ", "latitude": 11.83, "longitude": 42.59},
    {"name": "Dominica", "iso_code": "DM", "latitude": 15.41, "longitude": -61.37},
    {"name": "Dominican Republic", "iso_code": "DO", "latitude": 18.74, "longitude": -70.16},
    {"name": "Ecuador", "iso_code": "EC", "latitude": -1.83, "longitude": -78.18},
    {"name": "Egypt", "iso_code": "EG", "latitude": 26.82, "longitude": 30.80},
    {"name": "El Salvador", "iso_code": "SV", "latitude": 13.79, "longitude": -88.90},
    {"name": "Equatorial Guinea", "iso_code": "GQ", "latitude": 1.65, "longitude": 10.27},
    {"name": "Eritrea", "iso_code": "ER", "latitude": 15.18, "longitude": 39.78},
    {"name": "Estonia", "iso_code": "EE", "latitude": 58.60, "longitude": 25.01},
    {"name": "Eswatini", "iso_code": "SZ", "latitude": -26.52, "longitude": 31.47},
    {"name": "Ethiopia", "iso_code": "ET", "latitude": 9.15, "longitude": 40.49},
    {"name": "Fiji", "iso_code": "FJ", "latitude": -16.58, "longitude": 179.41},
    {"name": "Finland", "iso_code": "FI", "latitude": 61.92, "longitude": 25.75},
    {"name": "France", "iso_code": "FR", "latitude": 46.23, "longitude": 2.21},
    {"name": "Gabon", "iso_code": "GA", "latitude": -0.80, "longitude": 11.61},
    {"name": "Gambia", "iso_code": "GM", "latitude": 13.44, "longitude": -15.31},
    {"name": "Georgia", "iso_code": "GE", "latitude": 42.32, "longitude": 43.36},
    {"name": "Germany", "iso_code": "DE", "latitude": 51.17, "longitude": 10.45},
    {"name": "Ghana", "iso_code": "GH", "latitude": 7.95, "longitude": -1.02},
    {"name": "Greece", "iso_code": "GR", "latitude": 39.07, "longitude": 21.82},
    {"name": "Grenada", "iso_code": "GD", "latitude": 12.12, "longitude": -61.68},
    {"name": "Guatemala", "iso_code": "GT", "latitude": 15.78, "longitude": -90.23},
    {"name": "Guinea", "iso_code": "GN", "latitude": 9.95, "longitude": -11.61},
    {"name": "Guinea-Bissau", "iso_code": "GW", "latitude": 11.80, "longitude": -15.18},
    {"name": "Guyana", "iso_code": "GY", "latitude": 4.86, "longitude": -58.93},
    {"name": "Haiti", "iso_code": "HT", "latitude": 18.97, "longitude": -72.29},
    {"name": "Honduras", "iso_code": "HN", "latitude": 15.20, "longitude": -86.24},
    {"name": "Hungary", "iso_code": "HU", "latitude": 47.16, "longitude": 19.50},
    {"name": "Iceland", "iso_code": "IS", "latitude": 64.96, "longitude": -19.02},
    {"name": "India", "iso_code": "IN", "latitude": 20.59, "longitude": 78.96},
    {"name": "Indonesia", "iso_code": "ID", "latitude": -0.79, "longitude": 113.92},
    {"name": "Iran", "iso_code": "IR", "latitude": 32.43, "longitude": 53.69},
    {"name": "Iraq", "iso_code": "IQ", "latitude": 33.22, "longitude": 43.68},
    {"name": "Ireland", "iso_code": "IE", "latitude": 53.41, "longitude": -8.24},
    {"name": "Israel", "iso_code": "IL", "latitude": 31.05, "longitude": 34.85},
    {"name": "Italy", "iso_code": "IT", "latitude": 41.87, "longitude": 12.57},
    {"name": "Jamaica", "iso_code": "JM", "latitude": 18.11, "longitude": -77.30},
    {"name": "Japan", "iso_code": "JP", "latitude": 36.20, "longitude": 138.25},
    {"name": "Jordan", "iso_code": "JO", "latitude": 30.59, "longitude": 36.24},
    {"name": "Kazakhstan", "iso_code": "KZ", "latitude": 48.02, "longitude": 66.92},
    {"name": "Kenya", "iso_code": "KE", "latitude": -0.02, "longitude": 37.91},
    {"name": "Kiribati", "iso_code": "KI", "latitude": -3.37, "longitude": -168.73},
    {"name": "Kuwait", "iso_code": "KW", "latitude": 29.31, "longitude": 47.48},
    {"name": "Kyrgyzstan", "iso_code": "KG", "latitude": 41.20, "longitude": 74.77},
    {"name": "Laos", "iso_code": "LA", "latitude": 19.86, "longitude": 102.50},
    {"name": "Latvia", "iso_code": "LV", "latitude": 56.88, "longitude": 24.60},
    {"name": "Lebanon", "iso_code": "LB", "latitude": 33.85, "longitude": 35.86},
    {"name": "Lesotho", "iso_code": "LS", "latitude": -29.61, "longitude": 28.23},
    {"name": "Liberia", "iso_code": "LR", "latitude": 6.43, "longitude": -9.43},
    {"name": "Libya", "iso_code": "LY", "latitude": 26.34, "longitude": 17.23},
    {"name": "Liechtenstein", "iso_code": "LI", "latitude": 47.14, "longitude": 9.55},
    {"name": "Lithuania", "iso_code": "LT", "latitude": 55.17, "longitude": 23.88},
    {"name": "Luxembourg", "iso_code": "LU", "latitude": 49.82, "longitude": 6.13},
    {"name": "Madagascar", "iso_code": "MG", "latitude": -18.77, "longitude": 46.87},
    {"name": "Malawi", "iso_code": "MW", "latitude": -13.25, "longitude": 34.30},
    {"name": "Malaysia", "iso_code": "MY", "latitude": 4.21, "longitude": 108.96},
    {"name": "Maldives", "iso_code": "MV", "latitude": 3.20, "longitude": 73.22},
    {"name": "Mali", "iso_code": "ML", "latitude": 17.57, "longitude": -3.99},
    {"name": "Malta", "iso_code": "MT", "latitude": 35.94, "longitude": 14.38},
    {"name": "Marshall Islands", "iso_code": "MH", "latitude": 7.13, "longitude": 171.18},
    {"name": "Mauritania", "iso_code": "MR", "latitude": 21.01, "longitude": -10.94},
    {"name": "Mauritius", "iso_code": "MU", "latitude": -20.35, "longitude": 57.55},
    {"name": "Mexico", "iso_code": "MX", "latitude": 23.63, "longitude": -102.55},
    {"name": "Micronesia", "iso_code": "FM", "latitude": 7.43, "longitude": 150.55},
    {"name": "Moldova", "iso_code": "MD", "latitude": 47.41, "longitude": 28.37},
    {"name": "Monaco", "iso_code": "MC", "latitude": 43.75, "longitude": 7.40},
    {"name": "Mongolia", "iso_code": "MN", "latitude": 46.86, "longitude": 103.85},
    {"name": "Montenegro", "iso_code": "ME", "latitude": 42.71, "longitude": 19.37},
    {"name": "Morocco", "iso_code": "MA", "latitude": 31.79, "longitude": -7.09},
    {"name": "Mozambique", "iso_code": "MZ", "latitude": -18.67, "longitude": 35.53},
    {"name": "Myanmar", "iso_code": "MM", "latitude": 17.11, "longitude": 96.76},
    {"name": "Namibia", "iso_code": "NA", "latitude": -22.96, "longitude": 18.49},
    {"name": "Nauru", "iso_code": "NR", "latitude": -0.53, "longitude": 166.93},
    {"name": "Nepal", "iso_code": "NP", "latitude": 28.39, "longitude": 84.12},
    {"name": "Netherlands", "iso_code": "NL", "latitude": 52.13, "longitude": 5.29},
    {"name": "New Zealand", "iso_code": "NZ", "latitude": -40.90, "longitude": 174.89},
    {"name": "Nicaragua", "iso_code": "NI", "latitude": 12.87, "longitude": -85.21},
    {"name": "Niger", "iso_code": "NE", "latitude": 17.61, "longitude": 8.08},
    {"name": "Nigeria", "iso_code": "NG", "latitude": 9.08, "longitude": 8.68},
    {"name": "North Korea", "iso_code": "KP", "latitude": 40.34, "longitude": 127.51},
    {"name": "North Macedonia", "iso_code": "MK", "latitude": 41.61, "longitude": 21.75},
    {"name": "Norway", "iso_code": "NO", "latitude": 60.47, "longitude": 8.47},
    {"name": "Oman", "iso_code": "OM", "latitude": 21.51, "longitude": 55.92},
    {"name": "Pakistan", "iso_code": "PK", "latitude": 30.38, "longitude": 69.35},
    {"name": "Palau", "iso_code": "PW", "latitude": 7.52, "longitude": 134.58},
    {"name": "Palestine", "iso_code": "PS", "latitude": 31.95, "longitude": 35.23},
    {"name": "Panama", "iso_code": "PA", "latitude": 8.54, "longitude": -80.78},
    {"name": "Papua New Guinea", "iso_code": "PG", "latitude": -6.31, "longitude": 143.96},
    {"name": "Paraguay", "iso_code": "PY", "latitude": -23.44, "longitude": -58.44},
    {"name": "Peru", "iso_code": "PE", "latitude": -9.19, "longitude": -75.02},
    {"name": "Philippines", "iso_code": "PH", "latitude": 12.88, "longitude": 121.77},
    {"name": "Poland", "iso_code": "PL", "latitude": 51.92, "longitude": 19.15},
    {"name": "Portugal", "iso_code": "PT", "latitude": 39.40, "longitude": -8.22},
    {"name": "Qatar", "iso_code": "QA", "latitude": 25.35, "longitude": 51.18},
    {"name": "Romania", "iso_code": "RO", "latitude": 45.94, "longitude": 24.97},
    {"name": "Russia", "iso_code": "RU", "latitude": 61.52, "longitude": 105.32},
    {"name": "Rwanda", "iso_code": "RW", "latitude": -1.94, "longitude": 29.87},
    {"name": "Saint Kitts and Nevis", "iso_code": "KN", "latitude": 17.36, "longitude": -62.78},
    {"name": "Saint Lucia", "iso_code": "LC", "latitude": 13.91, "longitude": -60.98},
    {"name": "Saint Vincent and the Grenadines", "iso_code": "VC", "latitude": 13.25, "longitude": -61.20},
    {"name": "Samoa", "iso_code": "WS", "latitude": -13.76, "longitude": -172.10},
    {"name": "San Marino", "iso_code": "SM", "latitude": 43.94, "longitude": 12.46},
    {"name": "São Tomé and Príncipe", "iso_code": "ST", "latitude": 0.19, "longitude": 6.61},
    {"name": "Saudi Arabia", "iso_code": "SA", "latitude": 23.89, "longitude": 45.08},
    {"name": "Senegal", "iso_code": "SN", "latitude": 14.50, "longitude": -14.45},
    {"name": "Serbia", "iso_code": "RS", "latitude": 44.02, "longitude": 21.01},
    {"name": "Seychelles", "iso_code": "SC", "latitude": -4.68, "longitude": 55.49},
    {"name": "Sierra Leone", "iso_code": "SL", "latitude": 8.46, "longitude": -11.78},
    {"name": "Singapore", "iso_code": "SG", "latitude": 1.35, "longitude": 103.82},
    {"name": "Slovakia", "iso_code": "SK", "latitude": 48.67, "longitude": 19.70},
    {"name": "Slovenia", "iso_code": "SI", "latitude": 46.15, "longitude": 14.99},
    {"name": "Solomon Islands", "iso_code": "SB", "latitude": -9.64, "longitude": 160.16},
    {"name": "Somalia", "iso_code": "SO", "latitude": 5.15, "longitude": 46.20},
    {"name": "South Africa", "iso_code": "ZA", "latitude": -30.56, "longitude": 22.94},
    {"name": "South Korea", "iso_code": "KR", "latitude": 35.91, "longitude": 127.77},
    {"name": "South Sudan", "iso_code": "SS", "latitude": 6.88, "longitude": 31.31},
    {"name": "Spain", "iso_code": "ES", "latitude": 40.46, "longitude": -3.75},
    {"name": "Sri Lanka", "iso_code": "LK", "latitude": 7.87, "longitude": 80.77},
    {"name": "Sudan", "iso_code": "SD", "latitude": 12.86, "longitude": 30.22},
    {"name": "Suriname", "iso_code": "SR", "latitude": 3.92, "longitude": -56.03},
    {"name": "Sweden", "iso_code": "SE", "latitude": 60.13, "longitude": 18.64},
    {"name": "Switzerland", "iso_code": "CH", "latitude": 46.82, "longitude": 8.23},
    {"name": "Syria", "iso_code": "SY", "latitude": 34.80, "longitude": 38.99},
    {"name": "Taiwan", "iso_code": "TW", "latitude": 23.70, "longitude": 120.96},
    {"name": "Tajikistan", "iso_code": "TJ", "latitude": 38.86, "longitude": 71.28},
    {"name": "Tanzania", "iso_code": "TZ", "latitude": -6.37, "longitude": 34.89},
    {"name": "Thailand", "iso_code": "TH", "latitude": 15.87, "longitude": 100.99},
    {"name": "Timor-Leste", "iso_code": "TL", "latitude": -8.87, "longitude": 125.73},
    {"name": "Togo", "iso_code": "TG", "latitude": 8.62, "longitude": 0.82},
    {"name": "Tonga", "iso_code": "TO", "latitude": -21.18, "longitude": -175.20},
    {"name": "Trinidad and Tobago", "iso_code": "TT", "latitude": 10.69, "longitude": -61.22},
    {"name": "Tunisia", "iso_code": "TN", "latitude": 33.89, "longitude": 9.54},
    {"name": "Turkey", "iso_code": "TR", "latitude": 38.96, "longitude": 35.24},
    {"name": "Turkmenistan", "iso_code": "TM", "latitude": 38.97, "longitude": 59.56},
    {"name": "Tuvalu", "iso_code": "TV", "latitude": -7.11, "longitude": 177.65},
    {"name": "Uganda", "iso_code": "UG", "latitude": 1.37, "longitude": 32.29},
    {"name": "Ukraine", "iso_code": "UA", "latitude": 48.38, "longitude": 31.17},
    {"name": "United Arab Emirates", "iso_code": "AE", "latitude": 23.42, "longitude": 53.85},
    {"name": "United Kingdom", "iso_code": "GB", "latitude": 55.38, "longitude": -3.44},
    {"name": "United States", "iso_code": "US", "latitude": 37.09, "longitude": -95.71},
    {"name": "Uruguay", "iso_code": "UY", "latitude": -32.52, "longitude": -55.77},
    {"name": "Uzbekistan", "iso_code": "UZ", "latitude": 41.38, "longitude": 64.59},
    {"name": "Vanuatu", "iso_code": "VU", "latitude": -15.38, "longitude": 166.96},
    {"name": "Vatican City", "iso_code": "VA", "latitude": 41.90, "longitude": 12.45},
    {"name": "Venezuela", "iso_code": "VE", "latitude": 6.42, "longitude": -66.59},
    {"name": "Vietnam", "iso_code": "VN", "latitude": 14.06, "longitude": 108.28},
    {"name": "Yemen", "iso_code": "YE", "latitude": 15.55, "longitude": 48.52},
    {"name": "Zambia", "iso_code": "ZM", "latitude": -13.13, "longitude": 27.85},
    {"name": "Zimbabwe", "iso_code": "ZW", "latitude": -19.02, "longitude": 29.15},
]


def init_db() -> None:
    Base.metadata.create_all(bind=engine)
    _seed_countries()


def _seed_countries() -> None:
    from app.models.country import Country

    with Session(engine) as db:
        if db.query(Country).count() > 0:
            return
        for c in SEED_COUNTRIES:
            db.add(Country(**c))
        db.commit()
